# Generated by Django 5.0.4 on 2024-04-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0005_alter_reservation_reservation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_requested', models.BooleanField(default=False)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa_management_app.studentinfo')),
            ],
        ),
    ]
