# Generated by Django 5.0.4 on 2024-04-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0006_requestletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestletter',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
