# Generated by Django 5.0.4 on 2024-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0013_alter_studentinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='amphoe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='arrival_from',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='arrival_transportation_type',
            field=models.CharField(blank=True, choices=[('AIR', 'Airplane'), ('SEA', 'Sea'), ('LAND', 'Land')], max_length=4),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='passport_expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='passport_issue_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='passport_issue_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='passport_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='port_of_arrival',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='tambol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='visa_expire_date',
            field=models.DateField(blank=True),
        ),
    ]
