# Generated by Django 5.0.4 on 2024-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0016_userprofile_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, choices=[('Visa-extension', 'Visa Extension'), ('90-days-report', 'Report Submission'), ('No-Selection', 'No Selection'), ('Deposit-from-IAC', 'Deposit-from-IAC')], default='No-Selection', max_length=20),
        ),
    ]
