# Generated by Django 5.0.4 on 2024-12-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0017_alter_transaction_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_info',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='visa_management_app.userprofile'),
        ),
    ]
