# Generated by Django 5.0.4 on 2024-04-07 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('address_no', models.CharField(max_length=100)),
                ('road', models.CharField(blank=True, max_length=100)),
                ('tambol', models.CharField(max_length=100)),
                ('amphoe', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('passport_number', models.CharField(max_length=9)),
                ('passport_issue_date', models.DateField()),
                ('passport_issue_place', models.CharField(max_length=100)),
                ('passport_expiration_date', models.DateField()),
                ('visa_expire_date', models.DateField()),
                ('arrival_transportation_type', models.CharField(choices=[('AIR', 'Airplane'), ('SEA', 'Sea'), ('LAND', 'Land')], max_length=4)),
                ('arrival_from', models.CharField(max_length=100)),
                ('port_of_arrival', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('tm6_no', models.CharField(blank=True, max_length=20)),
                ('report_90_days_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
