# Generated by Django 5.0.4 on 2024-04-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
