# Generated by Django 5.0.4 on 2024-09-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0009_userprofile_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa_extension_status',
            field=models.BooleanField(default=False),
        ),
    ]
