# Generated by Django 5.0.4 on 2024-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0010_userprofile_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, choices=[('Visa-extension', 'Visa Extension'), ('90-days-report', 'Report Submission'), ('No-Selection', 'No Selection')], default='No-Selection', max_length=20),
        ),
    ]
