# Generated by Django 5.0.4 on 2024-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_management_app', '0015_alter_studentinfo_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
